name: Deploy to GH Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_VERSION: 24

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Setup pnpm/node ${{ env.NODE_VERSION }}
        uses: pnpm/setup@v2
        with:
          runtime: node@${{ env.NODE_VERSION }}
          cache: false

      - name: Build Astro site
        uses: withastro/action@v6
        with:
          path: ./packages/site
          node-version: ${{ env.NODE_VERSION }}
          package-manager: pnpm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to gh pages 🥁
        id: deployment
        uses: actions/deploy-pages@v5
