name: PR Checks

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 24

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Setup pnpm/node ${{ env.NODE_VERSION}}
        uses: pnpm/setup@v2
        with:
          runtime: node@${{ env.NODE_VERSION }}
          cache: true

      - name: Run linting
        run: pnpm lint

      - name: Run astro check
        run: pnpm check

  build:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Setup pnpm/node ${{ env.NODE_VERSION }}
        uses: pnpm/setup@v2
        with:
          runtime: node@${{ env.NODE_VERSION }}
          cache: true

      - name: Try building
        run: pnpm build

